apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-budget
  namespace: actual-budget
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Actual Budget
        property: oidc-client-id
      secretKey: ACTUAL_OPENID_CLIENT_ID
    - remoteRef:
        key: Actual Budget
        property: oidc-client-secret
      secretKey: ACTUAL_OPENID_CLIENT_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: actual-budget
