apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-budget
  namespace: actual-budget
spec:
  data:
    - remoteRef:
        key: actual-budget
        property: username
      secretKey: ACTUAL_OPENID_CLIENT_ID
    - remoteRef:
        key: actual-budget
        property: password
      secretKey: ACTUAL_OPENID_CLIENT_SECRET
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: actual-budget
