apiVersion: automation.excloo.dev/v1alpha1
kind: PocketIDClient
metadata:
  name: actual-budget
  namespace: actual-budget
spec:
  client:
    callbackURLs:
      - https://app.invalid/openid/callback
    description: Personal Finance
    id: actual-budget-au-truenas
    launchURL: https://app.invalid
    name: Actual Budget
