apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
  namespace: romm
  annotations:
    onepassword.excloo.dev/adopt-titles: RoMM
    onepassword.excloo.dev/generate-fields: auth-secret-key
    onepassword.excloo.dev/migrate-fields: '{"auth_secret_key":"auth-secret-key","db_password":"database-password","igdb_client_id":"igdb-client-id","igdb_client_secret":"igdb-client-secret","oidc_client_id":"oidc-client-id","oidc_client_secret":"oidc-client-secret","retroachievements_api_key":"retroachievements-api-key","screenscraper_password":"screenscraper-password","screenscraper_username":"screenscraper-username","steamgriddb_api_key":"steamgriddb-api-key"}'
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: RoMM
        property: auth-secret-key
      secretKey: ROMM_AUTH_SECRET_KEY
    - remoteRef:
        key: RoMM
        property: igdb-client-id
      secretKey: IGDB_CLIENT_ID
    - remoteRef:
        key: RoMM
        property: igdb-client-secret
      secretKey: IGDB_CLIENT_SECRET
    - remoteRef:
        key: RoMM
        property: oidc-client-id
      secretKey: OIDC_CLIENT_ID
    - remoteRef:
        key: RoMM
        property: oidc-client-secret
      secretKey: OIDC_CLIENT_SECRET
    - remoteRef:
        key: RoMM
        property: retroachievements-api-key
      secretKey: RETROACHIEVEMENTS_API_KEY
    - remoteRef:
        key: RoMM
        property: screenscraper-password
      secretKey: SCREENSCRAPER_PASSWORD
    - remoteRef:
        key: RoMM
        property: screenscraper-username
      secretKey: SCREENSCRAPER_USER
    - remoteRef:
        key: RoMM
        property: steamgriddb-api-key
      secretKey: STEAMGRIDDB_API_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: romm
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-database
  namespace: romm
  annotations:
    onepassword.excloo.dev/constants: '{"database-username":"romm"}'
    onepassword.excloo.dev/generate-fields: database-password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: RoMM
        property: database-password
      secretKey: password
    - remoteRef:
        key: RoMM
        property: database-username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: romm-database
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
