apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-data
  labels:
    app.kubernetes.io/name: romm
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Ti
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/truenas-nvme/romm
    server: 10.4.0.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-games
  labels:
    app.kubernetes.io/name: romm
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Ti
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/truenas/games
    server: 10.4.0.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
