apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: romm
  annotations:
    k8s-sigs.io/nfs-directory-gid: "26"
    k8s-sigs.io/nfs-directory-mode: "0700"
    k8s-sigs.io/nfs-directory-uid: "26"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeName: romm-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: ""
  volumeName: romm-games
