apiVersion: automation.excloo.dev/v1alpha1
kind: PocketIDClient
metadata:
  name: romm
  namespace: romm
spec:
  client:
    callbackURLs:
      - https://app.invalid/api/oauth/openid
    description: Game & ROM Library
    id: romm-au-truenas
    launchURL: https://app.invalid
    name: RoMM
