apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-secrets
  - gateway-api
  - local-path-provisioner
  - victoria-metrics
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        install:
          remediation:
            retries: 3
        upgrade:
          remediation:
            retries: 3
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
