apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Cloudflare Tunnel
        property: password
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: tunnel-token
