apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  data:
    - remoteRef:
        key: op://6bit6kovpdqaja5qilki5u2hvm/zurrg7dzcejnnaoa4mso7pe3be/password
      secretKey: token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: tunnel-token
