apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 30m
  releaseName: cloudflared
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.1.0
  values:
    controllers:
      cloudflared:
        strategy: RollingUpdate
        type: deployment
        containers:
          cloudflared:
            image:
              pullPolicy: IfNotPresent
              repository: cloudflare/cloudflared
              tag: 2026.8.3@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339
            args:
              - tunnel
              - --no-autoupdate
              - run
            env:
              - name: TUNNEL_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: token
                    name: tunnel-token
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 20m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
