apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beszel
  namespace: beszel
  annotations:
    onepassword.excloo.dev/defaults: '{"username":"admin@excloo.com"}'
    onepassword.excloo.dev/generate-fields: password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Beszel
        property: username
      secretKey: USER_EMAIL
    - remoteRef:
        key: Beszel
        property: password
      secretKey: USER_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: beszel
