apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - object-storage.yaml
  - pocket-id.yaml
  - private-dns.yaml
  - resources.yaml
patches:
  - path: settings.yaml
replacements:
  - source:
      kind: HelmRelease
      name: beszel
      namespace: beszel
      fieldPath: spec.values.route.private.hostnames.0
    targets:
      - select:
          kind: PrivateDNSRecord
          name: beszel
          namespace: beszel
        fieldPaths:
          - spec.hostname
      - select:
          kind: PocketIDClient
          name: beszel
          namespace: beszel
        fieldPaths:
          - spec.client.callbackURLs.0
          - spec.client.launchURL
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: beszel
          namespace: beszel
        fieldPaths:
          - spec.values.controllers.beszel.containers.beszel.env.APP_URL
          - spec.values.route.private.annotations.[gethomepage.dev/href]
          - spec.values.route.private.annotations.[gethomepage.dev/widget.url]
        options:
          delimiter: /
          index: 2
