apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beszel
  namespace: beszel
  annotations:
    onepassword.excloo.dev/defaults: '{"username":"admin@excloo.com"}'
    onepassword.excloo.dev/generate-fields: password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Beszel
        property: username
      secretKey: USER_EMAIL
    - remoteRef:
        key: Beszel
        property: password
      secretKey: USER_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: beszel
---
apiVersion: v1
kind: Namespace
metadata:
  name: beszel
  labels:
    app.kubernetes.io/name: beszel
    gateway.excloo.dev/private-access: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: beszel
  namespace: beszel
  labels:
    app.kubernetes.io/name: beszel
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: beszel-agent
          podSelector:
            matchLabels:
              app.kubernetes.io/name: beszel-agent
      ports:
        - port: 8090
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: networking
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 8090
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: beszel
  policyTypes:
    - Ingress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: beszel
  annotations:
    k8s-sigs.io/nfs-directory-gid: "568"
    k8s-sigs.io/nfs-directory-mode: "0700"
    k8s-sigs.io/nfs-directory-uid: "568"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: truenas-nfs
---
apiVersion: automation.excloo.dev/v1alpha1
kind: ResendKey
metadata:
  name: resend
  namespace: beszel
spec:
  displayName: Beszel
