apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 2.9.0
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    certController:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 32Mi
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 20m
        memory: 64Mi
    webhook:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 32Mi
