apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cloudflared.yaml
  - external-secrets.yaml
  - networking.yaml
  - storage.yaml
  - tailscale.yaml
