apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - settings.yaml
replacements:
  - source:
      kind: ConfigMap
      name: shared-settings
      fieldPath: data.beszel_host
    targets:
      - select:
          kind: PrivateDNSRecord
          name: beszel
          namespace: beszel
        fieldPaths:
          - spec.hostname
      - select:
          kind: PocketIDClient
          name: beszel
          namespace: beszel
        fieldPaths:
          - spec.client.callbackURLs.0
          - spec.client.launchURL
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: beszel
          namespace: beszel
        fieldPaths:
          - spec.values.controllers.beszel.containers.beszel.env.APP_URL
          - spec.values.route.private.annotations.[gethomepage.dev/href]
          - spec.values.route.private.annotations.[gethomepage.dev/widget.url]
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: beszel
          namespace: beszel
        fieldPaths:
          - spec.values.route.private.hostnames.0
  - source:
      kind: ConfigMap
      name: shared-settings
      fieldPath: data.control_d_profile
    targets:
      - select:
          kind: CompositeResourceDefinition
          name: privatednsrecords.automation.excloo.dev
        fieldPaths:
          - spec.versions.0.schema.openAPIV3Schema.properties.spec.properties.controlDProfileID.default
  - source:
      kind: ConfigMap
      name: shared-settings
      fieldPath: data.identity_host
    targets:
      - select:
          kind: HelmRelease
          name: actual-budget
          namespace: actual-budget
        fieldPaths:
          - spec.values.controllers.actual-budget.containers.actual-budget.env.ACTUAL_OPENID_DISCOVERY_URL
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: linkwarden
          namespace: linkwarden
        fieldPaths:
          - spec.values.controllers.linkwarden.containers.linkwarden.env.KEYCLOAK_ISSUER
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: miniflux
          namespace: miniflux
        fieldPaths:
          - spec.values.controllers.miniflux.containers.miniflux.env.OAUTH2_OIDC_DISCOVERY_ENDPOINT
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: open-webui
          namespace: open-webui
        fieldPaths:
          - spec.values.sso.oidc.providerUrl
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: pocket-id
          namespace: pocket-id
        fieldPaths:
          - spec.values.controllers.pocket-id.containers.pocket-id.env.APP_URL
          - spec.values.route.public.annotations.[gethomepage.dev/href]
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: pocket-id
          namespace: pocket-id
        fieldPaths:
          - spec.values.route.private.hostnames.0
          - spec.values.route.public.hostnames.0
      - select:
          kind: HelmRelease
          name: romm
          namespace: romm
        fieldPaths:
          - spec.values.controllers.romm.containers.romm.env.OIDC_SERVER_APPLICATION_URL
          - spec.values.controllers.romm.containers.romm.env.OIDC_SERVER_METADATA_URL
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: shelfmark
          namespace: shelfmark
        fieldPaths:
          - spec.values.controllers.shelfmark.containers.shelfmark.env.OIDC_DISCOVERY_URL
        options:
          delimiter: /
          index: 2
      - select:
          kind: PrivateDNSRecord
          name: pocket-id
          namespace: pocket-id
        fieldPaths:
          - spec.hostname
