[tools]
actionlint = "1.7.12"
flux2 = "2.9.4"
helm = "4.2.3"
kubeconform = "0.8.0"
kubectl = "1.36.3"
kustomize = "5.8.1"
prek = "0.4.14"
prettier = "3.9.6"
trivy = "0.74.0"
yq = "4.53.3"

# Setup
[tasks.setup]
description = "Install tools and Git hooks"
run = """
mise install
prek install
"""

# Development
[tasks.check]
description = "Check formatting and repository configuration"
run = """
set -o pipefail
actionlint .github/workflows/*.yaml
kubeconform_flags="-ignore-missing-schemas -kubernetes-version 1.36.3 -skip CustomResourceDefinition -strict -summary -schema-location default -schema-location {% raw %}https://raw.githubusercontent.com/datreeio/CRDs-catalog/becbe1103d096697610985b89f1630b2ab549982/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json{% endraw %}"
for target in $(
  {
    find clusters -mindepth 1 -maxdepth 1 -type d
    yq eval-all -N -r 'select(.apiVersion == "kustomize.toolkit.fluxcd.io/v1" and .kind == "Kustomization") | .spec.path' clusters/*/*.yaml
  } | sort -u
); do
  target="${target#./}"
  kustomize build "$target" | kubeconform $kubeconform_flags
done
prettier --check .
trivy config --exit-code 1 --severity HIGH,CRITICAL --ignorefile .trivyignore.yaml .
"""

[tasks.fmt]
description = "Format project files"
run = """
prettier --write .
"""

[tasks.prek]
description = "Run all repository hooks"
run = "prek run --all-files"
