apiVersion: automation.excloo.dev/v1alpha1
kind: B2ObjectStorage
metadata:
  name: beszel
  namespace: beszel
spec:
  displayName: Beszel
  keyName: beszel
  secretRef:
    name: beszel-object-storage
