apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: networking
spec:
  secretName: wildcard
  dnsNames:
    - "*.excloo.com"
    - "*.syd.excloo.dev"
    - www.reddit.excloo.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns01
