apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../platform
  - observability
  - certificate.yaml
  - gateway-public-direct.yaml
  - grafana.yaml
  - headlamp.yaml
patches:
  - path: secret-store.yaml
  - path: tailscale.yaml
  - path: traefik-gateway.yaml
  - path: traefik.yaml
