apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../platform
  - ../../../platform/automation/crossplane
  - observability
  - certificate.yaml
  - gateway-public-direct.yaml
  - grafana.yaml
  - headlamp.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/listeners/1/tls/certificateRefs/-
        value:
          name: redlib-www
    target:
      kind: Gateway
      name: private
  - patch: |-
      - op: replace
        path: /spec/values/resources/requests/cpu
        value: 10m
    target:
      kind: HelmRelease
      name: headlamp
  - path: secret-store.yaml
  - path: tailscale.yaml
  - path: traefik-gateway.yaml
  - path: traefik.yaml
replacements:
  - source:
      kind: HTTPRoute
      name: headlamp
      namespace: headlamp
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: HTTPRoute
          name: headlamp
          namespace: headlamp
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
        options:
          delimiter: /
          index: 2
  - source:
      kind: HTTPRoute
      name: grafana
      namespace: observability
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: HTTPRoute
          name: grafana
          namespace: observability
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
          - metadata.annotations.[gethomepage.dev/widget.url]
        options:
          delimiter: /
          index: 2
components:
  - ../settings
