apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../platform
  - ../../../platform/automation/crossplane
  - ../../../platform/databases/cloudnative-pg
  - ../../../platform/storage/truenas-nfs
  - observability
  - certificate.yaml
  - external-dns-private.yaml
  - grafana.yaml
  - headlamp.yaml
patches:
  - path: secret-store.yaml
  - path: tailscale.yaml
  - path: traefik-gateway.yaml
  - path: traefik.yaml
replacements:
  - source:
      kind: HTTPRoute
      name: headlamp
      namespace: headlamp
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: HTTPRoute
          name: headlamp
          namespace: headlamp
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
        options:
          delimiter: /
          index: 2
  - source:
      kind: HTTPRoute
      name: grafana
      namespace: observability
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: HTTPRoute
          name: grafana
          namespace: observability
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
          - metadata.annotations.[gethomepage.dev/widget.url]
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: victoria-metrics-k8s-stack
          namespace: observability
        fieldPaths:
          - spec.values.grafana.[grafana.ini].server.domain
      - select:
          kind: HelmRelease
          name: victoria-metrics-k8s-stack
          namespace: observability
        fieldPaths:
          - spec.values.grafana.[grafana.ini].server.root_url
        options:
          delimiter: /
          index: 2
      - select:
          kind: PrivateDNSRecord
          name: grafana
          namespace: observability
        fieldPaths:
          - spec.hostname
      - select:
          kind: PocketIDClient
          name: grafana
          namespace: observability
        fieldPaths:
          - spec.client.callbackURLs.0
          - spec.client.launchURL
        options:
          delimiter: /
          index: 2
components:
  - ../settings
