apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../platform
  - ../../../platform/storage/truenas-nfs
  - certificate.yaml
  - headlamp.yaml
patches:
  - path: observability.yaml
  - path: secret-store.yaml
  - path: tailscale.yaml
  - path: traefik.yaml
