apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  nfs:
    server: 10.4.0.3
    path: /mnt/truenas-nvme/kubernetes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truenas-nfs
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 10Gi
