apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  values:
    operatorConfig:
      hostname: mbk-operator
      defaultTags:
        - tag:mbk-operator
    proxyConfig:
      defaultTags: tag:mbk
