apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  values:
    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: mbk
        tailscale.com/tailnet-ip: 100.109.10.13
