apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: beszel-agent
  labels:
    app.kubernetes.io/name: beszel-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: beszel-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: beszel-agent
    spec:
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: beszel-agent
          env:
            - name: DATA_DIR
              value: /var/lib/beszel-agent
            - name: HUB_URL
              value: https://beszel-agent.mbk.excloo.dev
            - name: KEY
              value: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPkxnKuxsVqSVZVXQ3OGHjZZFMAAclU/xLrEDdwOyRt+
            - name: LISTEN
              value: "45876"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: beszel-agent
          image: henrygd/beszel-agent:0.18.8
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /agent
                - health
            periodSeconds: 120
            timeoutSeconds: 5
          ports:
            - name: agent
              containerPort: 45876
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /agent
                - health
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          startupProbe:
            exec:
              command:
                - /agent
                - health
            failureThreshold: 30
            periodSeconds: 2
          volumeMounts:
            - name: data
              mountPath: /var/lib/beszel-agent
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - name: data
          emptyDir: {}
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
