apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beszel-agent
  namespace: beszel-agent
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: beszel-agent/password
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: beszel-agent
