apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redlib-www
  namespace: networking
spec:
  secretName: redlib-www
  dnsNames:
    - www.app.invalid
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns01
