apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redlib
  namespace: redlib
spec:
  data:
    - remoteRef:
        key: redlib/password
      secretKey: ctrld-endpoint
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: redlib
