apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redlib
  namespace: redlib
  annotations:
    onepassword.excloo.dev/adopt-titles: Redlib (redlib)
    onepassword.excloo.dev/migrate-fields: '{"ctrld_endpoint_rw":"resolver-id-control-d","monitoring_token_rw":"monitoring-token"}'
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Redlib
        property: monitoring-token
      secretKey: monitoring-token
    - remoteRef:
        key: Redlib
        property: resolver-id-control-d
      secretKey: ctrld-endpoint
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: redlib
