apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redlib
  namespace: redlib
spec:
  interval: 30m
  releaseName: redlib
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.2.1
  values:
    controllers:
      redlib:
        strategy: RollingUpdate
        containers:
          ctrld:
            args:
              - --cd=$(CTRLD_ENDPOINT)
            command:
              - /ctrld
              - run
            workingDir: /etc/controld
            env:
              CTRLD_ENDPOINT:
                valueFrom:
                  secretKeyRef:
                    key: ctrld-endpoint
                    name: redlib
            image:
              pullPolicy: IfNotPresent
              repository: controldns/ctrld
              tag: 1.5.7@sha256:85d4f083103541c114d55b80b0a14dfc0a2411b3ee227b2e15be29562b4dc4f6
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 65534
              runAsNonRoot: true
              runAsUser: 65534
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
          redlib:
            workingDir: /etc/redlib
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/maxexcloo/redlib
              tag: sha-5c3d1a6@sha256:b433bdde33e9beb10dd72d3cb3ed1e8861cf86311d0e2a895bd36c805fe8c712
            probes:
              liveness:
                enabled: true
                path: /settings
                port: 8080
                type: HTTP
              readiness:
                enabled: true
                path: /settings
                port: 8080
                type: HTTP
              startup:
                enabled: true
                path: /settings
                port: 8080
                type: HTTP
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 20m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
    defaultPodOptions:
      automountServiceAccountToken: false
      dnsConfig:
        nameservers:
          - 127.0.0.1
      dnsPolicy: None
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    global:
      nameOverride: redlib
    persistence:
      config:
        name: redlib-config
        type: configMap
        advancedMounts:
          redlib:
            redlib:
              - path: /etc/redlib
                readOnly: true
      controld:
        type: emptyDir
        advancedMounts:
          redlib:
            ctrld:
              - path: /etc/controld
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          gethomepage.dev/description: Reddit Frontend
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Applications
          gethomepage.dev/href: https://reddit.excloo.com
          gethomepage.dev/icon: redlib
          gethomepage.dev/name: Redlib
          gethomepage.dev/siteMonitor: https://reddit.excloo.com
        hostnames:
          - reddit.excloo.com
        labels:
          app.kubernetes.io/name: redlib
          gateway.excloo.dev/public-access: "true"
        parentRefs:
          - name: public-tunnel
            namespace: networking
    service:
      redlib:
        controller: redlib
        ports:
          http:
            port: 8080
            protocol: HTTP
