apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redlib
  namespace: redlib
spec:
  interval: 30m
  releaseName: redlib
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.1.0
  values:
    controllers:
      redlib:
        containers:
          ctrld:
            args:
              - --cd=$(CTRLD_ENDPOINT)
            command:
              - /ctrld
              - run
            workingDir: /etc/controld
            env:
              CTRLD_ENDPOINT:
                valueFrom:
                  secretKeyRef:
                    key: ctrld-endpoint
                    name: redlib
            image:
              pullPolicy: IfNotPresent
              repository: controldns/ctrld
              tag: 1.5.5@sha256:60df8936d53488400b0b53c50aed39f8db344aa0aa1b6b70e27d2a36caa65129
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 65534
              runAsNonRoot: true
              runAsUser: 65534
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
          redlib:
            env:
              REDLIB_DEFAULT_REMOVE_DEFAULT_FEEDS: "on"
              REDLIB_DEFAULT_SUBSCRIPTIONS: anime_titties+apple+askanaustralian+askhistorians+askscience+auscorp+ausfinance+auspropertychat+aussiefrugal+australia+australiannostalgia+bazzite+boxoffice+budgetaudiophile+cars+carsaustralia+catastrophicfailure+chatgptcoding+crackwatch+cscareerquestionsoce+datahoarder+deepseek+docker+eink+electricvehicles+emulation+emulationonandroid+esphome+flashlight+flipperzero+games+handhelds+hardware+homeassistant+homelab+homenetworking+homeserver+immich+internetisbeautiful+korea+linux+linux_gaming+linuxhardware+living_in_korea+llmdevs+localllama+localllm+meshcore+minilab+minimalism+minipcs+moonlightstreaming+movies+nbn+netsec+networking+nixos+odinhandheld+onebag+opencode+opensource+openwrt+organizationporn+outoftheloop+pikvm+piratedgames+praisethecameraman+privacy+programming+proxmox+raspberry_pi+retroarch+retroid+roms+sbcgaming+sbcs+selfhosted+sffpc+sideloaded+sideproject+singularity+solotravel+space+steamdeck+sydney+sydneyscene+sydneytrains+sysadmin+tailscale+television+thatlookedexpensive+trance+travel+travelhacks+trimui+truenas+ubiquiti+usbchardware+wallstreetbets+wled+zfs+zigbee
              REDLIB_DEFAULT_USE_HLS: "on"
              REDLIB_FULL_URL: https://reddit.excloo.com
              REDLIB_ROBOTS_DISABLE_INDEXING: "on"
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/nachtalb/redlib
              tag: latest@sha256:8d3672ad029114482e6265bf90172be23b1d4164a1e1af531383a935c6fb1da4
            probes:
              liveness:
                enabled: true
                path: /settings
                port: 8080
                type: HTTP
              readiness:
                enabled: true
                path: /settings
                port: 8080
                type: HTTP
              startup:
                enabled: true
                path: /settings
                port: 8080
                type: HTTP
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 20m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      automountServiceAccountToken: false
      dnsConfig:
        nameservers:
          - 127.0.0.1
      dnsPolicy: None
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    global:
      nameOverride: redlib
    persistence:
      controld:
        type: emptyDir
        advancedMounts:
          redlib:
            ctrld:
              - path: /etc/controld
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      redlib:
        controller: redlib
        annotations:
          gethomepage.dev/description: Reddit Frontend
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: redlib
          gethomepage.dev/name: Redlib
        ports:
          http:
            port: 8080
            protocol: HTTP
