apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare.yaml
  - helm-release.yaml
  - private-dns.yaml
  - private-redirect.yaml
  - redirect.yaml
  - resources.yaml
patches:
  - path: settings.yaml
