apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redlib
  namespace: redlib
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Redlib
        property: resolver-id-control-d
      secretKey: ctrld-endpoint
    - remoteRef:
        key: Redlib
        property: monitoring-token
      secretKey: monitoring-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: redlib
---
apiVersion: v1
kind: Namespace
metadata:
  name: redlib
  labels:
    app.kubernetes.io/name: redlib
    gateway.excloo.dev/public-access: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redlib
  namespace: redlib
  labels:
    app.kubernetes.io/name: redlib
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: networking
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redlib
  policyTypes:
    - Ingress
