apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redlib
  namespace: redlib
spec:
  values:
    controllers:
      redlib:
        containers:
          redlib:
            env:
              REDLIB_DEFAULT_REMOVE_DEFAULT_FEEDS: on
              REDLIB_DEFAULT_USE_HLS: on
              REDLIB_ROBOTS_DISABLE_INDEXING: on
    subscriptions:
      - anime_titties
      - apple
      - askanaustralian
      - askhistorians
      - askscience
      - auscorp
      - ausfinance
      - auspropertychat
      - aussiefrugal
      - australia
      - australiannostalgia
      - bazzite
      - boxoffice
      - budgetaudiophile
      - cars
      - carsaustralia
      - catastrophicfailure
      - chatgptcoding
      - crackwatch
      - cscareerquestionsoce
      - datahoarder
      - deepseek
      - docker
      - eink
      - electricvehicles
      - emulation
      - emulationonandroid
      - esphome
      - flashlight
      - flipperzero
      - games
      - handhelds
      - hardware
      - homeassistant
      - homelab
      - homenetworking
      - homeserver
      - immich
      - internetisbeautiful
      - korea
      - linux
      - linux_gaming
      - linuxhardware
      - living_in_korea
      - llmdevs
      - localllama
      - localllm
      - meshcore
      - minilab
      - minimalism
      - minipcs
      - moonlightstreaming
      - movies
      - nbn
      - netsec
      - networking
      - nixos
      - odinhandheld
      - onebag
      - opencode
      - opensource
      - openwrt
      - organizationporn
      - outoftheloop
      - pikvm
      - comfyui
      - stablediffusion
      - praisethecameraman
      - privacy
      - programming
      - proxmox
      - raspberry_pi
      - retroarch
      - retroid
      - roms
      - sbcgaming
      - sbcs
      - selfhosted
      - sffpc
      - sideloaded
      - singularity
      - solotravel
      - space
      - steamdeck
      - sydney
      - sydneyscene
      - sydneytrains
      - sysadmin
      - tailscale
      - television
      - thatlookedexpensive
      - trance
      - travel
      - travelhacks
      - trimui
      - truenas
      - ubiquiti
      - usbchardware
      - wallstreetbets
      - wled
      - zfs
      - zigbee
    route:
      public:
        hostnames:
          - reddit.excloo.com
        annotations:
          gethomepage.dev/description: Reddit Frontend
          gethomepage.dev/enabled: "true"
          monitoring.excloo.dev/enabled: "true"
          monitoring.excloo.dev/headers: '{"x-gatus-token":{"name":"redlib","key":"monitoring-token"}}'
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: redlib
          gethomepage.dev/name: Redlib
