apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: observability
  annotations:
    onepassword.excloo.dev/adopt-titles: Grafana
    onepassword.excloo.dev/defaults: '{"username":"max@excloo.com"}'
    onepassword.excloo.dev/migrate-fields: '{"oidc_client_id":"oidc-client-id","oidc_client_secret":"oidc-client-secret"}'
spec:
  data:
    - remoteRef:
        key: Grafana
        property: oidc-client-id
      secretKey: oidc-client-id
    - remoteRef:
        key: Grafana
        property: oidc-client-secret
      secretKey: oidc-client-secret
    - remoteRef:
        key: Grafana
        property: password
      secretKey: password
    - remoteRef:
        key: Grafana
        property: username
      secretKey: username
