apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: observability
  annotations:
    onepassword.excloo.dev/adopt-titles: Grafana
    onepassword.excloo.dev/migrate-fields: '{"oidc_client_id":"oidc-client-id","oidc_client_secret":"oidc-client-secret"}'
