apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - namespace-node.yaml
  - namespace.yaml
  - network-policy.yaml
  - source.yaml
  - vlagent-cluster-role-binding.yaml
  - vlagent-cluster-role.yaml
