apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cliproxyapi
  namespace: cliproxyapi
spec:
  data:
    - remoteRef:
        key: cliproxyapi
        property: api-key
      secretKey: apiKey
    - remoteRef:
        key: cliproxyapi
        property: management-key
      secretKey: managementKey
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: cliproxyapi
    template:
      engineVersion: v2
      data:
        config.yaml: |
          port: 8317
          auth-dir: /data
          api-keys:
            - "{{ .apiKey }}"
          remote-management:
            allow-remote: true
            secret-key: "{{ .managementKey }}"
          usage-statistics-enabled: true
