apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cliproxyapi
  namespace: cliproxyapi
spec:
  interval: 30m
  releaseName: cliproxyapi
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.1.0
  values:
    controllers:
      cliproxyapi:
        strategy: Recreate
        containers:
          cliproxyapi:
            env:
              TZ: Australia/Sydney
            image:
              pullPolicy: IfNotPresent
              repository: docker.io/eceasy/cli-proxy-api
              tag: v7.2.128
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  httpGet:
                    path: /
                    port: 8317
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                custom: true
                enabled: true
                spec:
                  httpGet:
                    path: /
                    port: 8317
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 30
                  httpGet:
                    path: /
                    port: 8317
                  periodSeconds: 2
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
    global:
      nameOverride: cliproxyapi
    persistence:
      config:
        name: cliproxyapi
        type: secret
        advancedMounts:
          cliproxyapi:
            cliproxyapi:
              - path: /CLIProxyAPI/config.yaml
                readOnly: true
                subPath: config.yaml
      data:
        existingClaim: data
        type: persistentVolumeClaim
        globalMounts:
          - path: /data
      static:
        type: emptyDir
        globalMounts:
          - path: /CLIProxyAPI/static
      temporary:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      cliproxyapi:
        controller: cliproxyapi
        ports:
          http:
            port: 8317
            protocol: HTTP
