apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: bookorbit
  annotations:
    k8s-sigs.io/nfs-directory-gid: "26"
    k8s-sigs.io/nfs-directory-mode: "0700"
    k8s-sigs.io/nfs-directory-uid: "26"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookdrop
  namespace: bookorbit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: bookorbit-bookdrop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books
  namespace: bookorbit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: bookorbit-books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: bookorbit
  annotations:
    k8s-sigs.io/nfs-directory-gid: "568"
    k8s-sigs.io/nfs-directory-mode: "0700"
    k8s-sigs.io/nfs-directory-uid: "568"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: truenas-nfs
