apiVersion: automation.excloo.dev/v1alpha1
kind: PocketIDClient
metadata:
  name: bookorbit
  namespace: bookorbit
spec:
  accessPolicy: books
  client:
    callbackURLs:
      - https://app.invalid/oauth2-callback
    description: Digital Library
    id: bookorbit-au-truenas
    launchURL: https://app.invalid
    name: BookOrbit
