apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark
  namespace: shelfmark
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: shelfmark
        property: googlebooks-api-key
      secretKey: GOOGLEBOOKS_API_KEY
    - remoteRef:
        key: shelfmark
        property: hardcover-api-key
      secretKey: HARDCOVER_API_KEY
    - remoteRef:
        key: shelfmark
        property: oidc-client-id
      secretKey: OIDC_CLIENT_ID
    - remoteRef:
        key: shelfmark
        property: password
      secretKey: OIDC_CLIENT_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: shelfmark
