apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark
  namespace: shelfmark
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Shelfmark
        property: api-key-googlebooks
      secretKey: GOOGLEBOOKS_API_KEY
    - remoteRef:
        key: Shelfmark
        property: api-key-hardcover
      secretKey: HARDCOVER_API_KEY
    - remoteRef:
        key: Shelfmark
        property: oidc-client-id
      secretKey: OIDC_CLIENT_ID
    - remoteRef:
        key: Shelfmark
        property: oidc-client-secret
      secretKey: OIDC_CLIENT_SECRET
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: shelfmark
