apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - pocket-id.yaml
  - private-dns.yaml
  - resources.yaml
patches:
  - path: settings.yaml
replacements:
  - source:
      kind: HelmRelease
      name: shelfmark
      namespace: shelfmark
      fieldPath: spec.values.route.public.hostnames.0
    targets:
      - select:
          kind: PrivateDNSRecord
          name: shelfmark
          namespace: shelfmark
        fieldPaths:
          - spec.hostname
      - select:
          kind: PocketIDClient
          name: shelfmark
          namespace: shelfmark
        fieldPaths:
          - spec.client.callbackURLs.0
          - spec.client.launchURL
        options:
          delimiter: /
          index: 2
      - select:
          kind: HelmRelease
          name: shelfmark
          namespace: shelfmark
        fieldPaths:
          - spec.values.route.private.hostnames.0
      - select:
          kind: HelmRelease
          name: shelfmark
          namespace: shelfmark
        fieldPaths:
          - spec.values.route.public.annotations.[gethomepage.dev/href]
        options:
          delimiter: /
          index: 2
