apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shelfmark
  namespace: shelfmark
  labels:
    app.kubernetes.io/name: shelfmark
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: networking
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 3000
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: shelfmark
  policyTypes:
    - Ingress
