apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -control-d-only
resources:
  - ../composition
patches:
  - patch: |-
      - op: test
        path: /spec/pipeline/0/input/resources/0/name
        value: cloudflare-record
      - op: remove
        path: /spec/pipeline/0/input/resources/0
    target:
      kind: Composition
      name: private-dns-record
