apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: windmill-database
  namespace: windmill
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie@sha256:37ade18dbdddba430858c72725aceeec66f33fa5333e82ea1df4942f6c1c83a3
  instances: 1
  bootstrap:
    initdb:
      database: windmill
      owner: windmill
      secret:
        name: windmill-database
  managed:
    roles:
      - name: windmill_user
        ensure: present
      - name: windmill_admin
        ensure: present
        inRoles:
          - windmill_user
      - name: windmill
        ensure: present
        inRoles:
          - windmill_admin
          - windmill_user
        login: true
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  storage:
    size: 10Gi
    storageClass: local-path
