apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-database
  namespace: windmill
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: database-windmill/password
      secretKey: password
    - remoteRef:
        key: database-windmill/username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: windmill-database
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        url: "postgres://{{ .username | urlquery }}:{{ .password | urlquery }}@windmill-postgresql:5432/windmill?sslmode=disable"
        username: "{{ .username }}"
