apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-database
  namespace: windmill
  annotations:
    onepassword.excloo.dev/constants: '{"database-username":"windmill"}'
    onepassword.excloo.dev/generate-fields: database-password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Windmill
        property: database-password
      secretKey: password
    - remoteRef:
        key: Windmill
        property: database-username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: windmill-database
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        url: "postgres://{{ .username | urlquery }}:{{ .password | urlquery }}@windmill-database-rw:5432/windmill?sslmode=require"
        username: "{{ .username }}"
