apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: windmill
  namespace: windmill
spec:
  interval: 30m
  releaseName: windmill
  chart:
    spec:
      chart: windmill
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: flux-system
      version: 4.0.245
  values:
    ingress:
      enabled: false
    postgresql:
      enabled: false
    serviceAccount:
      automountServiceAccountToken: false
    windmill:
      appReplicas: 1
      baseDomain: windmill
      baseProtocol: https
      databaseUrlAsFile: true
      databaseUrlSecretName: windmill-database
      disableUnsharePid: true
      extraReplicas: 1
      imagePullPolicy: IfNotPresent
      app:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      windmillExtra:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
      workerGroups:
        - name: default
          disableUnsharePid: true
          privileged: false
          replicas: 1
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
