apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup.yaml
  - database.yaml
  - helm-release.yaml
  - login.yaml
  - postgresql.yaml
  - resources.yaml
  - source.yaml
