apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates/cert-manager
  - identity/headlamp
  - networking/cilium
  - networking/cloudflared
  - networking/external-dns
  - networking/tailscale
  - networking/traefik
  - secrets/external-secrets
  - secrets/onepassword-connect
  - secrets/onepassword-items
  - sources/bjw-s.yaml
  - sources/cilium.yaml
  - sources/external-dns.yaml
  - sources/headlamp.yaml
  - sources/onepassword.yaml
  - sources/tailscale.yaml
  - sources/traefik.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        install:
          remediation:
            retries: 3
        upgrade:
          remediation:
            retries: 3
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
