apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates/cert-manager
  - namespaces
  - networking/cilium
  - networking/traefik
  - secrets/external-secrets
  - sources/cert-manager
  - sources/cilium
  - sources/external-secrets
  - sources/traefik
