apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificates/cert-manager
  - identity
  - namespaces
  - networking/cilium
  - networking/cloudflared
  - networking/tailscale
  - networking/traefik
  - secrets/external-secrets
  - storage/truenas-nfs
  - sources/bjw-s
  - sources/cert-manager
  - sources/cilium
  - sources/external-secrets
  - sources/headlamp
  - sources/openspeedtest
  - sources/tailscale
  - sources/traefik
