apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost
  namespace: bifrost
spec:
  data:
    - remoteRef:
        key: Bifrost
        property: api-key
      secretKey: BIFROST_API_KEY
    - remoteRef:
        key: Bifrost
        property: api-key-cliproxy
      secretKey: CLIPROXY_API_KEY
    - remoteRef:
        key: Bifrost
        property: api-key-comfy-control
      secretKey: COMFY_CONTROL_API_KEY
    - remoteRef:
        key: Bifrost
        property: encryption-key
      secretKey: encryption-key
    - remoteRef:
        key: Bifrost
        property: password
      secretKey: password
    - remoteRef:
        key: Bifrost
        property: username
      secretKey: username
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: bifrost
