apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost
  namespace: bifrost
spec:
  data:
    - remoteRef:
        key: bifrost/api-key
      secretKey: BIFROST_API_KEY
    - remoteRef:
        key: bifrost/cliproxy-api-key
      secretKey: CLIPROXY_API_KEY
    - remoteRef:
        key: bifrost/comfy-control-api-key
      secretKey: COMFY_CONTROL_API_KEY
    - remoteRef:
        key: bifrost/encryption-key
      secretKey: encryption-key
    - remoteRef:
        key: bifrost/password
      secretKey: password
    - remoteRef:
        key: bifrost/username
      secretKey: username
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: bifrost
