apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bifrost
  namespace: bifrost
  annotations:
    gethomepage.dev/description: LLM Gateway
    gethomepage.dev/enabled: "true"
    monitoring.excloo.dev/enabled: "true"
    monitoring.excloo.dev/path: /health
    gethomepage.dev/group: Artificial Intelligence
    gethomepage.dev/href: https://app.invalid
    gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/maximhq/bifrost/ui/public/bifrost-icon-dark.webp
    gethomepage.dev/name: Bifrost
  labels:
    app.kubernetes.io/name: bifrost
spec:
  hostnames:
    - bifrost.excloo.com
  parentRefs:
    - name: private
      namespace: networking
  rules:
    - backendRefs:
        - name: bifrost
          port: 8080
