apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-syd
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  grafana_host: grafana.syd.excloo.dev
  private_dns_host: private.syd.excloo.dev
  # Derived from private_dns_host by Kustomize.
  private_dns_lookup: https://cloudflare-dns.com/dns-query?name=app.invalid
