apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-acme-token
  namespace: cert-manager
spec:
  data:
    - remoteRef:
        key: cloudflare-acme/password
      secretKey: api-token
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: cloudflare-api-token
