apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 41.2.0
  values:
    accessLog:
      enabled: true
      format: json
    deployment:
      replicas: 1
    gateway:
      enabled: true
      name: private
      listeners:
        web:
          port: 8000
          protocol: HTTP
          namespacePolicy:
            from: All
        websecure:
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - name: wildcard
          namespacePolicy:
            from: All
    gatewayClass:
      enabled: true
      name: traefik
    ingressClass:
      enabled: false
    log:
      format: json
      level: INFO
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 256Mi
    service:
      spec:
        type: ClusterIP
