apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 41.2.0
  values:
    accessLog:
      enabled: true
      format: json
    deployment:
      replicas: 1
    gateway:
      enabled: false
    gatewayClass:
      enabled: true
      name: traefik
    ingressClass:
      enabled: false
    log:
      format: json
      level: INFO
    ports:
      webtunnel:
        exposedPort: 80
        port: 8081
        protocol: TCP
        expose:
          default: false
          tunnel: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 256Mi
    service:
      additionalServices:
        tunnel:
          spec:
            type: ClusterIP
      spec:
        type: ClusterIP
