apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 40.2.0
  releaseName: traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: values.yaml
