apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: networking
spec:
  chart:
    spec:
      chart: traefik-crds
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 1.18.0
  interval: 30m
  releaseName: traefik-crds
