apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aiostreams
  namespace: aiostreams
  annotations:
    onepassword.excloo.dev/adopt-titles: AIOStreams
    onepassword.excloo.dev/defaults: '{"username":"max@excloo.com"}'
    onepassword.excloo.dev/generate-fields: password,secret-key
    onepassword.excloo.dev/migrate-fields: '{"secret_key":"secret-key"}'
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: AIOStreams
        property: password
      secretKey: PASSWORD
    - remoteRef:
        key: AIOStreams
        property: secret-key
      secretKey: SECRET_KEY
    - remoteRef:
        key: AIOStreams
        property: username
      secretKey: USERNAME
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: aiostreams
    template:
      data:
        AIOSTREAMS_AUTH: "{{ .USERNAME }}:{{ .PASSWORD }}"
        SECRET_KEY: "{{ .SECRET_KEY }}"
