apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aiostreams
  namespace: aiostreams
spec:
  interval: 30m
  releaseName: aiostreams
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.2.1
  values:
    controllers:
      aiostreams:
        strategy: Recreate
        containers:
          aiostreams:
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/viren070/aiostreams
              tag: v2.34.1@sha256:70c0f2de448bcc1e39dd6a2db3f45585ab4e2d6d35761d2264047d8f38078b74
            env:
              BASE_URL: https://aiostreams.excloo.com
              DATABASE_URI: sqlite://./data/db.sqlite
              FEATURED_TEMPLATE_IDS: tamtaro.complete,Vidhin05.english-template
              PORT: "30375"
              SEL_SYNC_ACCESS: all
              TEMPLATE_REFRESH_INTERVAL: "3600"
              TEMPLATE_URLS: '["https://raw.githubusercontent.com/Tam-Taro/SEL-Filtering-and-Sorting/bd0dee43bdf7e262cf9fc7ebf8402ad94057fb2b/Tamtaro-All-Templates-for-AIOStreams.json", "https://raw.githubusercontent.com/Vidhin05/Releases-Regex/b75a607fbb96fee63a44c30f403d1e6399d9c8fe/all-templates.json"]'
              WHITELISTED_SYNC_REFRESH_INTERVAL: "3600"
            envFrom:
              - secretRef:
                  name: aiostreams
            probes:
              liveness:
                enabled: true
                path: /api/v1/health
                port: 30375
                type: HTTP
              readiness:
                enabled: true
                path: /api/v1/health
                port: 30375
                type: HTTP
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 568
              runAsNonRoot: true
              runAsUser: 568
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
    global:
      nameOverride: aiostreams
    persistence:
      data:
        existingClaim: data
        type: persistentVolumeClaim
        globalMounts:
          - path: /app/data
      temporary:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      main:
        annotations:
          gethomepage.dev/description: Stremio Aggregator
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/href: https://aiostreams.excloo.com
          gethomepage.dev/icon: sh-aiostreams
          gethomepage.dev/name: AIOStreams
        hostnames:
          - aiostreams.excloo.com
        labels:
          app.kubernetes.io/name: aiostreams
        parentRefs:
          - name: private
            namespace: networking
    service:
      aiostreams:
        controller: aiostreams
        ports:
          http:
            port: 30375
            protocol: HTTP
