apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-database
  namespace: miniflux
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie@sha256:37ade18dbdddba430858c72725aceeec66f33fa5333e82ea1df4942f6c1c83a3
  instances: 1
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
      secret:
        name: miniflux-database
  storage:
    size: 5Gi
    storageClass: local-path
