apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
  namespace: miniflux
  annotations:
    onepassword.excloo.dev/constants: '{"database-username":"miniflux"}'
    onepassword.excloo.dev/defaults: '{"username":"admin"}'
    onepassword.excloo.dev/generate-fields: database-password,password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Miniflux
        property: database-password
      secretKey: database-password
    - remoteRef:
        key: Miniflux
        property: database-username
      secretKey: database-username
    - remoteRef:
        key: Miniflux
        property: oauth-client-id
      secretKey: OAUTH2_CLIENT_ID
    - remoteRef:
        key: Miniflux
        property: oauth-client-secret
      secretKey: OAUTH2_CLIENT_SECRET
    - remoteRef:
        key: Miniflux
        property: password
      secretKey: password
    - remoteRef:
        key: Miniflux
        property: username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: miniflux
    template:
      engineVersion: v2
      data:
        ADMIN_PASSWORD: "{{ .password }}"
        ADMIN_USERNAME: "{{ .username }}"
        DATABASE_URL: 'postgres://{{ index . "database-username" | urlquery }}:{{ index . "database-password" | urlquery }}@miniflux-database-rw:5432/miniflux?sslmode=require'
        OAUTH2_CLIENT_ID: "{{ .OAUTH2_CLIENT_ID }}"
        OAUTH2_CLIENT_SECRET: "{{ .OAUTH2_CLIENT_SECRET }}"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-database
  namespace: miniflux
  annotations:
    onepassword.excloo.dev/constants: '{"database-username":"miniflux"}'
    onepassword.excloo.dev/generate-fields: database-password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Miniflux
        property: database-password
      secretKey: password
    - remoteRef:
        key: Miniflux
        property: database-username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: miniflux-database
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
