apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux
  namespace: miniflux
spec:
  interval: 30m
  releaseName: miniflux
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.1.0
  values:
    controllers:
      miniflux:
        strategy: Recreate
        containers:
          miniflux:
            env:
              BASE_URL: https://reader.excloo.com
              OAUTH2_OIDC_DISCOVERY_ENDPOINT: https://id.excloo.com
              OAUTH2_OIDC_PROVIDER_NAME: Excloo ID
              OAUTH2_PROVIDER: oidc
              OAUTH2_REDIRECT_URL: https://reader.excloo.com/oauth2/oidc/callback
              OAUTH2_USER_CREATION: "1"
              RUN_MIGRATIONS: "1"
              TZ: Australia/Sydney
            envFrom:
              - secretRef:
                  name: miniflux
            image:
              pullPolicy: IfNotPresent
              repository: docker.io/miniflux/miniflux
              tag: 2.3.3@sha256:49d7b60987616387c306a8023087b31f2c9b7b21288b523026cb04058e8b6dbb
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 20m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
    global:
      nameOverride: miniflux
    persistence:
      temporary:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      miniflux:
        controller: miniflux
        ports:
          http:
            port: 8080
            protocol: HTTP
    route:
      main:
        annotations:
          gethomepage.dev/description: Feed Reader
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Applications
          gethomepage.dev/href: https://reader.excloo.com
          gethomepage.dev/icon: miniflux
          gethomepage.dev/name: Miniflux
        hostnames:
          - reader.excloo.com
        labels:
          app.kubernetes.io/name: miniflux
        parentRefs:
          - name: private
            namespace: networking
