apiVersion: automation.excloo.dev/v1alpha1
kind: PocketIDClient
metadata:
  name: miniflux
  namespace: miniflux
spec:
  client:
    callbackURLs:
      - https://app.invalid/oauth2/oidc/callback
    description: RSS Reader
    id: miniflux-au-truenas
    launchURL: https://app.invalid
    name: Miniflux
