apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Tailscale Kubernetes Operator
        property: username
      secretKey: client_id
    - remoteRef:
        key: Tailscale Kubernetes Operator
        property: password
      secretKey: client_secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: operator-oauth
