apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  data:
    - remoteRef:
        key: g4osooqtv75hghesoglcpmmuuq
        property: username
      secretKey: client-id
    - remoteRef:
        key: g4osooqtv75hghesoglcpmmuuq
        property: password
      secretKey: client-secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: operator-oauth
    template:
      data:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
