apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  data:
    - remoteRef:
        key: op://6bit6kovpdqaja5qilki5u2hvm/g4osooqtv75hghesoglcpmmuuq/username
      secretKey: client_id
    - remoteRef:
        key: op://6bit6kovpdqaja5qilki5u2hvm/g4osooqtv75hghesoglcpmmuuq/password
      secretKey: client_secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: operator-oauth
