apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 20m
            memory: 128Mi
