apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: observability
spec:
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: local-path-provisioner
      namespace: storage
    - name: onepassword-connect
      namespace: external-secrets
  values:
    grafana:
      admin:
        existingSecret: grafana
        passwordKey: password
        userKey: username
      resources:
        requests:
          cpu: 25m
    kube-state-metrics:
      resources:
        requests:
          cpu: 10m
    victoria-metrics-operator:
      resources:
        requests:
          cpu: 20m
    vlagent:
      spec:
        resources:
          requests:
            cpu: 20m
    vlsingle:
      spec:
        resources:
          requests:
            cpu: 20m
    vmagent:
      spec:
        externalLabels:
          cluster: syd
        resources:
          requests:
            cpu: 20m
    vmsingle:
      spec:
        resources:
          requests:
            cpu: 25m
