apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: anisette
  namespace: anisette
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  labels:
    app.kubernetes.io/name: anisette
    gateway.excloo.dev/public-access: "true"
spec:
  hostnames:
    - anisette.excloo.com
  parentRefs:
    - name: public-direct
      namespace: networking
      sectionName: websecuredirect
  rules:
    - backendRefs:
        - name: anisette
          port: 6969
