apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/anisette
  - ../../base/openspeedtest
  - anisette-route.yaml
  - route.yaml
patches:
  - path: helm-release-homepage.yaml
