apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/anisette
  - ../../base/beszel-agent
  - ../../base/openspeedtest
  - ../../base/redlib
  - openspeedtest-route.yaml
patches:
  - path: beszel-agent.yaml
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: _
        annotations:
          kustomize.toolkit.fluxcd.io/substitute: disabled
    target:
      kind: ConfigMap
  - patch: |-
      - op: replace
        path: /spec/values/resources/requests/cpu
        value: 10m
    target:
      kind: HelmRelease
      name: openspeedtest
replacements:
  - source:
      kind: HTTPRoute
      name: openspeedtest
      namespace: openspeedtest
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: HTTPRoute
          name: openspeedtest
          namespace: openspeedtest
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
        options:
          delimiter: /
          index: 2
components:
  - ../../../clusters/syd/settings
