apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aiometadata
  namespace: aiometadata
  annotations:
    onepassword.excloo.dev/adopt-titles: AIOMetadata
    onepassword.excloo.dev/generate-fields: password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: AIOMetadata
        property: password
      secretKey: ADMIN_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: aiometadata
