apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aiometadata
  namespace: aiometadata
spec:
  interval: 30m
  releaseName: aiometadata
  suspend: false
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.1.0
  values:
    controllers:
      aiometadata:
        strategy: Recreate
        containers:
          aiometadata:
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/cedya77/aiometadata
              tag: 2.15.0@sha256:3bbdcb47202c62eb66a664ef923c661e43f6a1eb0be7d2eebe26d029093fddd2
            env:
              DATABASE_URI: sqlite://addon/data/db.sqlite
              HOST_NAME: https://aiometadata.excloo.com
              REDIS_URL: redis://localhost:6379
            envFrom:
              - secretRef:
                  name: aiometadata
            probes:
              liveness:
                enabled: true
                path: /health/live
                port: 3232
                type: HTTP
              readiness:
                enabled: true
                path: /health/ready
                port: 3232
                type: HTTP
              startup:
                enabled: true
                path: /health/live
                port: 3232
                type: HTTP
                spec:
                  failureThreshold: 12
                  periodSeconds: 5
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
          redis:
            image:
              pullPolicy: IfNotPresent
              repository: docker.io/library/redis
              tag: 8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
            args: [redis-server, --appendonly, "no", --save, ""]
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
              readiness:
                custom: true
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 20m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 999
              runAsNonRoot: true
              runAsUser: 999
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    global:
      nameOverride: aiometadata
    persistence:
      data:
        existingClaim: data
        type: persistentVolumeClaim
        advancedMounts:
          aiometadata:
            aiometadata:
              - path: /app/addon/data
      redis:
        type: emptyDir
        advancedMounts:
          aiometadata:
            redis:
              - path: /data
      temporary:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      aiometadata:
        controller: aiometadata
        ports:
          http:
            port: 3232
            protocol: HTTP
    route:
      main:
        annotations:
          gethomepage.dev/description: Stremio Metadata
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/href: https://aiometadata.excloo.com
          gethomepage.dev/icon: sh-aiometadata
          gethomepage.dev/name: AIOMetadata
        hostnames:
          - aiometadata.excloo.com
        labels:
          app.kubernetes.io/name: aiometadata
        parentRefs:
          - name: private
            namespace: networking
