apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: aiometadata
  annotations:
    k8s-sigs.io/nfs-directory-gid: "1000"
    k8s-sigs.io/nfs-directory-mode: "0700"
    k8s-sigs.io/nfs-directory-uid: "1000"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: truenas-nfs
