apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: larapaper
  namespace: larapaper
spec:
  data:
    - remoteRef:
        key: Larapaper
        property: password
      secretKey: APP_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: larapaper
