apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: larapaper
  namespace: larapaper
  annotations:
    onepassword.excloo.dev/migrate-fields: '{"password":"app-key"}'
    onepassword.excloo.dev/remove-fields: password
spec:
  data:
    - remoteRef:
        key: Larapaper
        property: app-key
      secretKey: APP_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: larapaper
