apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: larapaper
  namespace: larapaper
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: LaraPaper
        property: app-key
      secretKey: APP_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: larapaper
