apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: larapaper
  annotations:
    k8s-sigs.io/nfs-directory-gid: "82"
    k8s-sigs.io/nfs-directory-mode: "0700"
    k8s-sigs.io/nfs-directory-uid: "82"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: truenas-nfs
