apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: beszel-agent
  namespace: beszel
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  labels:
    app.kubernetes.io/name: beszel
    gateway.excloo.dev/public-access: "true"
spec:
  hostnames:
    - beszel-agent.mbk.excloo.dev
  parentRefs:
    - name: public-tunnel
      namespace: networking
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/beszel/agent-connect
      backendRefs:
        - name: beszel
          port: 8090
