apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  values:
    controllers:
      homepage:
        initContainers:
          endpoints:
            env:
              HOMEPAGE_CLUSTER: mbk
