apiVersion: automation.excloo.dev/v1alpha1
kind: PrivateDNSRecord
metadata:
  name: immich
  namespace: immich
spec:
  hostname: photos.excloo.com
  ipv6Enabled: false
  crossplane:
    compositionRef:
      name: private-dns-record-control-d-only
