apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/actual-budget
  - ../../base/actual-up
  - ../../base/aiometadata
  - ../../base/aiostreams
  - ../../base/beszel
  - ../../base/beszel-agent
  - ../../base/bichon
  - ../../base/bifrost
  - ../../base/bookorbit
  - ../../base/cliproxyapi
  - ../../base/comfy-control
  - ../../base/homepage
  - ../../base/immich
  - ../../base/larapaper
  - ../../base/linkwarden
  - ../../base/miniflux
  - ../../base/open-webui
  - ../../base/openspeedtest
  - ../../base/papra
  - ../../base/pocket-id
  - ../../base/romm
  - ../../base/shelfmark
  - ../../base/sidestore-vpn
  - homepage-private-dns.yaml
  - immich-private-route.yaml
  - openspeedtest-route.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: _
        annotations:
          kustomize.toolkit.fluxcd.io/substitute: disabled
    target:
      kind: ConfigMap
  - patch: |-
      - op: add
        path: /spec/cluster
        value: mbk
    target:
      group: automation.excloo.dev
      kind: ResendKey
      version: v1alpha1
  - path: beszel-agent.yaml
  - path: homepage.yaml
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: actual-budget
        namespace: actual-budget
      spec:
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: networking
                podSelector:
                  matchLabels:
                    app.kubernetes.io/name: traefik
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: actual-up
                podSelector:
                  matchLabels:
                    app.kubernetes.io/name: actual-up
            ports:
              - port: 5006
                protocol: TCP
replacements:
  - source:
      kind: HTTPRoute
      name: openspeedtest
      namespace: openspeedtest
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: HTTPRoute
          name: openspeedtest
          namespace: openspeedtest
        fieldPaths:
          - metadata.annotations.[gethomepage.dev/href]
        options:
          delimiter: /
          index: 2
  - source:
      kind: HTTPRoute
      name: immich
      namespace: immich
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: HTTPRoute
          name: immich-private
        fieldPaths:
          - spec.hostnames.0
components:
  - ../../../clusters/mbk/settings
