apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/actual-budget
  - ../../base/aiometadata
  - ../../base/aiostreams
  - ../../base/beszel
  - ../../base/beszel-agent
  - ../../base/bichon
  - ../../base/bifrost
  - ../../base/bookorbit
  - ../../base/byparr
  - ../../base/cliproxyapi
  - ../../base/comfy-control
  - ../../base/homepage
  - ../../base/immich
  - ../../base/larapaper
  - ../../base/linkwarden
  - ../../base/miniflux
  - ../../base/open-webui
  - ../../base/openspeedtest
  - ../../base/papra
  - ../../base/pocket-id
  - ../../base/romm
  - ../../base/shelfmark
  - ../../base/windmill
  - bifrost-route.yaml
  - immich-route.yaml
  - route.yaml
  - windmill-route.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/cluster
        value: mbk
    target:
      group: automation.excloo.dev
      kind: ResendKey
      version: v1alpha1
  - path: beszel-agent.yaml
  - path: windmill-domain.yaml
