apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/beszel
  - ../../base/beszel-agent
  - ../../base/byparr
  - ../../base/homepage
  - ../../base/openspeedtest
  - ../../base/windmill
  - beszel-agent-route.yaml
  - beszel-route.yaml
  - byparr-route.yaml
  - homepage-route.yaml
  - route.yaml
  - windmill-route.yaml
patches:
  - path: windmill-domain.yaml
