apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comfy-control
  namespace: comfy-control
  annotations:
    onepassword.excloo.dev/defaults: '{"username":"admin"}'
    onepassword.excloo.dev/generate-fields: api-key-control,control-secret-key,password
    onepassword.excloo.dev/login: "true"
spec:
  data:
    - remoteRef:
        key: Comfy Control
        property: civitai-token
      secretKey: CIVITAI_TOKEN
    - remoteRef:
        key: CLIProxyAPI
        property: api-key
      secretKey: CLIPROXY_API_KEY
    - remoteRef:
        key: CLIProxyAPI
        property: management-key
      secretKey: CLIPROXY_MANAGEMENT_KEY
    - remoteRef:
        key: Comfy Control
        property: api-key-control
      secretKey: CONTROL_API_KEY
    - remoteRef:
        key: Comfy Control
        property: control-secret-key
      secretKey: CONTROL_SECRET_KEY
    - remoteRef:
        key: Comfy Control
        property: password
      secretKey: CONTROL_UI_PASSWORD
    - remoteRef:
        key: Comfy Control
        property: username
      secretKey: CONTROL_UI_USERNAME
    - remoteRef:
        key: Comfy Control
        property: hf-token
      secretKey: HF_TOKEN
    - remoteRef:
        key: Comfy Control
        property: modal-token-id
      secretKey: MODAL_TOKEN_ID
    - remoteRef:
        key: Comfy Control
        property: modal-token-secret
      secretKey: MODAL_TOKEN_SECRET
    - remoteRef:
        key: Comfy Control
        property: api-key-runpod
      secretKey: RUNPOD_API_KEY
    - remoteRef:
        key: Comfy Control
        property: api-key-salad
      secretKey: SALAD_API_KEY
    - remoteRef:
        key: Comfy Control
        property: salad-organisation
      secretKey: SALAD_ORGANISATION
    - remoteRef:
        key: Comfy Control
        property: salad-project
      secretKey: SALAD_PROJECT
    - remoteRef:
        key: Comfy Control
        property: api-key-vast
      secretKey: VAST_API_KEY
    - remoteRef:
        key: Comfy Control
        property: api-key-worker
      secretKey: WORKER_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: comfy-control
