apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comfy-control
  namespace: comfy-control
spec:
  data:
    - remoteRef:
        key: comfy-control
        property: civitai-token
      secretKey: CIVITAI_TOKEN
    - remoteRef:
        key: cliproxyapi
        property: api-key
      secretKey: CLIPROXY_API_KEY
    - remoteRef:
        key: cliproxyapi
        property: management-key
      secretKey: CLIPROXY_MANAGEMENT_KEY
    - remoteRef:
        key: comfy-control
        property: control-api-key
      secretKey: CONTROL_API_KEY
    - remoteRef:
        key: comfy-control
        property: control-secret-key
      secretKey: CONTROL_SECRET_KEY
    - remoteRef:
        key: comfy-control
        property: password
      secretKey: CONTROL_UI_PASSWORD
    - remoteRef:
        key: comfy-control
        property: username
      secretKey: CONTROL_UI_USERNAME
    - remoteRef:
        key: comfy-control
        property: hf-token
      secretKey: HF_TOKEN
    - remoteRef:
        key: comfy-control
        property: modal-token-id
      secretKey: MODAL_TOKEN_ID
    - remoteRef:
        key: comfy-control
        property: modal-token-secret
      secretKey: MODAL_TOKEN_SECRET
    - remoteRef:
        key: comfy-control
        property: runpod-api-key
      secretKey: RUNPOD_API_KEY
    - remoteRef:
        key: comfy-control
        property: salad-api-key
      secretKey: SALAD_API_KEY
    - remoteRef:
        key: comfy-control
        property: salad-organisation
      secretKey: SALAD_ORGANISATION
    - remoteRef:
        key: comfy-control
        property: salad-project
      secretKey: SALAD_PROJECT
    - remoteRef:
        key: comfy-control
        property: vast-api-key
      secretKey: VAST_API_KEY
    - remoteRef:
        key: comfy-control
        property: worker-api-key
      secretKey: WORKER_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: comfy-control
