apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comfy-control
  namespace: comfy-control
spec:
  data:
    - remoteRef:
        key: comfy-control/civitai-token
      secretKey: CIVITAI_TOKEN
    - remoteRef:
        key: cliproxyapi/api-key
      secretKey: CLIPROXY_API_KEY
    - remoteRef:
        key: cliproxyapi/management-key
      secretKey: CLIPROXY_MANAGEMENT_KEY
    - remoteRef:
        key: comfy-control/control-api-key
      secretKey: CONTROL_API_KEY
    - remoteRef:
        key: comfy-control/control-secret-key
      secretKey: CONTROL_SECRET_KEY
    - remoteRef:
        key: comfy-control/password
      secretKey: CONTROL_UI_PASSWORD
    - remoteRef:
        key: comfy-control/username
      secretKey: CONTROL_UI_USERNAME
    - remoteRef:
        key: comfy-control/hf-token
      secretKey: HF_TOKEN
    - remoteRef:
        key: comfy-control/modal-token-id
      secretKey: MODAL_TOKEN_ID
    - remoteRef:
        key: comfy-control/modal-token-secret
      secretKey: MODAL_TOKEN_SECRET
    - remoteRef:
        key: comfy-control/runpod-api-key
      secretKey: RUNPOD_API_KEY
    - remoteRef:
        key: comfy-control/salad-api-key
      secretKey: SALAD_API_KEY
    - remoteRef:
        key: comfy-control/salad-organisation
      secretKey: SALAD_ORGANISATION
    - remoteRef:
        key: comfy-control/salad-project
      secretKey: SALAD_PROJECT
    - remoteRef:
        key: comfy-control/vast-api-key
      secretKey: VAST_API_KEY
    - remoteRef:
        key: comfy-control/worker-api-key
      secretKey: WORKER_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: comfy-control
