apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - private-dns.yaml
  - resources.yaml
patches:
  - path: settings.yaml
replacements:
  - source:
      kind: HelmRelease
      name: comfy-control
      namespace: comfy-control
      fieldPath: spec.values.route.private.hostnames.0
    targets:
      - select:
          kind: PrivateDNSRecord
          name: comfy-control
          namespace: comfy-control
        fieldPaths:
          - spec.hostname
      - select:
          kind: HelmRelease
          name: comfy-control
          namespace: comfy-control
        fieldPaths:
          - spec.values.route.private.annotations.[gethomepage.dev/href]
        options:
          delimiter: /
          index: 2
