apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bichon
  namespace: bichon
  annotations:
    onepassword.excloo.dev/generate-fields: encryption-password
    onepassword.excloo.dev/migrate-fields: '{"password":"encryption-password"}'
    onepassword.excloo.dev/remove-fields: password,username
spec:
  data:
    - remoteRef:
        key: Bichon
        property: encryption-password
      secretKey: BICHON_ENCRYPT_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: bichon
