apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bichon
  namespace: bichon
spec:
  data:
    - remoteRef:
        key: bichon
        property: password
      secretKey: BICHON_ENCRYPT_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: bichon
