apiVersion: v1
kind: PersistentVolume
metadata:
  name: bichon-data
  labels:
    app.kubernetes.io/name: bichon
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/truenas-nvme/bichon
    server: 10.4.0.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
