apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Providers:
        - 1Password:
            - description: Passwords & Secrets
              href: https://my.1password.com
              icon: si-1password-#ffffff
        - Backblaze:
            - description: Object Storage
              href: https://backblaze.com
              icon: si-backblaze-#ffffff
        - Cloudflare:
            - description: DNS & Zero Trust
              href: https://dash.cloudflare.com
              icon: si-cloudflare-#ffffff
        - Control D:
            - description: DNS
              href: https://controld.com
              icon: sh-control-d-light
        - Fly.io:
            - description: App Platform
              href: https://fly.io/dashboard
              icon: si-flydotio-#ffffff
        - GitHub:
            - description: Source Control
              href: https://github.com/maxexcloo
              icon: si-github-#ffffff
        - Oracle Cloud:
            - description: Cloud VMs
              href: https://cloud.oracle.com
              icon: si-oracle-#ffffff
        - Resend:
            - description: Email API
              href: https://resend.com/overview
              icon: si-resend-#ffffff
        - Tailscale:
            - description: VPN
              href: https://login.tailscale.com/admin
              icon: si-tailscale-#ffffff
        - UniFi:
            - description: Network
              href: https://unifi.ui.com
              icon: si-ubiquiti-#ffffff
  custom.css: |
    :root {
      --homepage-card-bg: rgba(0, 0, 0, 0.15);
      --homepage-card-radius: 15px;
      --tw-shadow-color: none;
    }
    html,
    body {
      -webkit-font-smoothing: auto !important;
      font-size: 110% !important;
      text-rendering: auto !important;
    }
    .rounded,
    .rounded-md {
      border-radius: var(--homepage-card-radius) !important;
    }
    .bookmark > a,
    .service-card {
      background: var(--homepage-card-bg) !important;
      box-shadow: none !important;
    }
    .service-card {
      transition: none !important;
    }
    .service-block {
      background: transparent !important;
    }
    .service-container {
      background: var(--homepage-card-bg) !important;
      border-radius: var(--homepage-card-radius);
    }
    .service-card > *:nth-child(n + 3) > div {
      margin-top: 0 !important;
      padding-top: 0 !important;
    }
    .service-title {
      position: relative;
    }
    .service-tags {
      bottom: 0;
    }
    .site-monitor-status {
      height: 100%;
      padding: 8px !important;
    }
    .site-monitor-status > .rounded-full {
      border-radius: var(--homepage-card-radius) !important;
      height: 100% !important;
      width: 6px !important;
    }
  docker.yaml: |
    {}
  kubernetes.yaml: |
    gateway: true
    ingress: false
    mode: cluster
    traefik: false
  services.yaml: |
    - Home Automation:
        - ESPHome:
            description: ESP Device Builder
            href: https://hass.mbk.excloo.net/5c53de3b_esphome
            icon: esphome
            siteMonitor: https://hass.mbk.excloo.net/5c53de3b_esphome
            weight: 0
        - ESPresense:
            description: Room Presence
            href: https://hass.mbk.excloo.net/f32ea98b_espresense-companion
            icon: espressif
            siteMonitor: https://hass.mbk.excloo.net/f32ea98b_espresense-companion
            weight: 0
        - Home Assistant:
            description: Smart Home & Automations
            href: https://hass.mbk.excloo.net
            icon: home-assistant
            siteMonitor: https://hass.mbk.excloo.net
            weight: -100
            widget:
              hideErrors: true
              key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_KEY}}"
              type: homeassistant
              url: https://hass.mbk.excloo.net
        - Home Assistant Matter Hub:
            description: Matter Bridge
            href: https://hass.mbk.excloo.net/3fd9e6b0_hamh
            icon: sh-home-assistant-matter-hub
            siteMonitor: https://hass.mbk.excloo.net/3fd9e6b0_hamh
            weight: 0
        - Studio Code Server:
            description: Browser IDE
            href: https://hass.mbk.excloo.net/a0d7b954_vscode
            icon: visual-studio-code
            siteMonitor: https://hass.mbk.excloo.net/a0d7b954_vscode
            weight: 0
        - Zigbee2MQTT:
            description: Zigbee Coordinator
            href: https://hass.mbk.excloo.net/45df7312_zigbee2mqtt
            icon: zigbee2mqtt
            siteMonitor: https://hass.mbk.excloo.net/45df7312_zigbee2mqtt
            weight: 0
    - Infrastructure:
        - Netboot:
            description: Network Boot Server
            href: http://kimbap.mbk.excloo.net:31010
            icon: netbootxyz
            siteMonitor: http://kimbap.mbk.excloo.net:31010
            weight: 0
        - Syncthing:
            description: File Synchronisation
            href: http://kimbap.mbk.excloo.net:20910
            icon: syncthing
            siteMonitor: http://kimbap.mbk.excloo.net:20910
            weight: 0
        - TrueNAS:
            description: Storage Appliance
            href: https://kimbap.mbk.excloo.net:8443
            icon: truenas
            siteMonitor: https://kimbap.mbk.excloo.net:8443
            weight: -100
            widget:
              enablePools: true
              hideErrors: true
              key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"
              type: truenas
              url: https://kimbap.mbk.excloo.net:8443
              version: 2
        - UniFi:
            description: Network Controller
            href: https://gateway.mbk.excloo.net
            icon: unifi
            siteMonitor: https://gateway.mbk.excloo.net
            weight: -100
            widget:
              hideErrors: true
              key: "{{HOMEPAGE_VAR_UNIFI_KEY}}"
              type: unifi
              url: https://gateway.mbk.excloo.net
    - Operations:
        - Gatus:
            description: Health Monitoring & Status Page
            href: https://status.excloo.com
            icon: gatus
            siteMonitor: https://status.excloo.com
            weight: -100
            widget:
              type: gatus
              url: https://status.excloo.com
  settings.yaml: |
    cardBlur: xs
    color: slate
    disableCollapse: true
    disableIndexing: true
    headerStyle: clean
    hideVersion: true
    statusStyle: dot
    theme: dark
    title: Homepage
    background:
      brightness: 50
      image: /images/background.jpg
    layout:
      Applications:
        columns: 4
        style: row
        tab: Services
      Artificial Intelligence:
        columns: 2
        style: row
        tab: Services
      Media:
        columns: 4
        style: row
        tab: Services
      Operations:
        columns: 2
        style: row
        tab: Services
      Providers:
        columns: 2
        style: row
        tab: Services
      Home Automation:
        columns: 4
        style: row
        tab: Servers
      Infrastructure:
        columns: 2
        style: row
        tab: Servers
  widgets.yaml: |
    - kubernetes:
        cluster:
          cpu: true
          label: "{{HOMEPAGE_VAR_CLUSTER}}"
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - search:
        provider: google
        target: _blank
