apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: homepage
  annotations:
    onepassword.excloo.dev/defaults: '{"beszel-password":"","beszel-username":"admin@excloo.com","home-assistant-key":"","immich-key":"","linkwarden-key":"","miniflux-key":"","tailscale-key":"","truenas-key":"","unifi-key":""}'
    onepassword.excloo.dev/migrate-fields: '{"tailscale_homepage_widget_key":"tailscale-key"}'
    onepassword.excloo.dev/remove-fields: tailscale_homepage_widget_key
spec:
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: Homepage
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: homepage
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_BESZEL_PASSWORD: '{{ index . "beszel-password" }}'
        HOMEPAGE_VAR_BESZEL_USERNAME: '{{ index . "beszel-username" }}'
        HOMEPAGE_VAR_HOME_ASSISTANT_KEY: '{{ index . "home-assistant-key" }}'
        HOMEPAGE_VAR_IMMICH_KEY: '{{ index . "immich-key" }}'
        HOMEPAGE_VAR_LINKWARDEN_KEY: '{{ index . "linkwarden-key" }}'
        HOMEPAGE_VAR_MINIFLUX_KEY: '{{ index . "miniflux-key" }}'
        HOMEPAGE_VAR_TAILSCALE_KEY: '{{ index . "tailscale-key" }}'
        HOMEPAGE_VAR_TRUENAS_KEY: '{{ index . "truenas-key" }}'
        HOMEPAGE_VAR_UNIFI_KEY: '{{ index . "unifi-key" }}'
