apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  values:
    route:
      private:
        hostnames:
          - home.excloo.com
          - homepage.mbk.excloo.dev
        annotations:
          gethomepage.dev/description: Application Dashboard
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: homepage
          gethomepage.dev/name: Homepage
          monitoring.excloo.dev/enabled: "true"
    controllers:
      homepage:
        containers:
          homepage:
            env:
              PGID: "1000"
              PUID: "1000"
