- Smart Home:
    - ESPHome:
        description: ESP Device Builder
        href: homelab://mbk/hass/management/5c53de3b_esphome
        icon: esphome
    - ESPresense Companion:
        description: Room Presence
        href: homelab://mbk/hass/management/f32ea98b_espresense-companion
        icon: espressif
    - Home Assistant:
        description: Smart Home & Automations
        href: &home_assistant homelab://mbk/hass/management
        icon: home-assistant
        siteMonitor: *home_assistant
        widget:
          key: "{{HOMEPAGE_FILE_HOME_ASSISTANT_KEY}}"
          type: homeassistant
          url: *home_assistant
    - Home Assistant Matter Hub:
        description: Matter Bridge
        href: homelab://mbk/hass/management/3fd9e6b0_hamh
        icon: sh-home-assistant-matter-hub
    - Studio Code Server:
        description: Browser IDE
        href: homelab://mbk/hass/management/a0d7b954_vscode
        icon: visual-studio-code
    - Zigbee2MQTT:
        description: Zigbee Coordinator
        href: homelab://mbk/hass/management/45df7312_zigbee2mqtt
        icon: zigbee2mqtt
- Infrastructure:
    - Netboot:
        description: Network Boot Server
        href: &netboot homelab://mbk/kimbap/netboot
        icon: netbootxyz
        siteMonitor: *netboot
    - Syncthing:
        description: File Synchronisation
        href: &syncthing homelab://mbk/kimbap/syncthing
        icon: syncthing
        siteMonitor: *syncthing
        widget:
          key: "{{HOMEPAGE_FILE_SYNCTHING_KEY}}"
          type: syncthing
          url: *syncthing
- Servers:
    - TrueNAS:
        description: Storage Appliance
        href: &truenas homelab://mbk/kimbap/management
        icon: truenas
        siteMonitor: *truenas
        widget:
          enablePools: true
          key: "{{HOMEPAGE_FILE_TRUENAS_KEY}}"
          type: truenas
          url: *truenas
          version: 2
    - UniFi:
        description: Network Controller
        href: &unifi homelab://mbk/gateway/management
        icon: unifi
        siteMonitor: *unifi
        widget:
          key: "{{HOMEPAGE_FILE_UNIFI_KEY}}"
          type: unifi
          url: *unifi
- Operations:
    - Gatus:
        description: Health Monitoring & Status Page • Fly
        href: &gatus homelab-dns://excloo-gatus.fly.dev
        icon: gatus
        siteMonitor: *gatus
        widget:
          type: gatus
          url: *gatus
