apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - resources.yaml
configMapGenerator:
  - name: actual-up-config
    namespace: actual-up
    files:
      - config.yaml
configurations:
  - kustomizeconfig.yaml
