apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-dns
  namespace: external-dns
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: cloudflare-external-dns/password
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: cloudflare-api-token
