apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.21.1
  values:
    domainFilters: [excloo.com, excloo.dev]
    labelFilter: gateway.excloo.dev/public-access=true
    logFormat: json
    managedRecordTypes: [A, AAAA, CNAME]
    policy: upsert-only
    registry: noop
    sources: [gateway-httproute]
    triggerLoopOnEvent: true
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: token
            name: cloudflare-api-token
    extraArgs:
      cloudflare-dns-records-per-page: "5000"
      cloudflare-record-comment: Managed by ExternalDNS
    provider:
      name: cloudflare
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi
