apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: observability
  annotations:
    onepassword.excloo.dev/defaults: '{"username":"admin"}'
    onepassword.excloo.dev/generate-fields: password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Grafana
        property: username
      secretKey: username
    - remoteRef:
        key: Grafana
        property: password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: grafana
