apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30m
  path: ./apps/overlays/mbk
  prune: true
  retryInterval: 2m
  timeout: 10m
  wait: true
  healthCheckExprs:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      current: (has(spec.suspend) && spec.suspend) || status.conditions.exists(e, e.type == 'Ready' && e.status == 'True' && e.observedGeneration == metadata.generation)
      failed: "(!has(spec.suspend) || !spec.suspend) && status.conditions.exists(e, e.type == 'Ready' && e.status == 'False' && e.observedGeneration == metadata.generation)"
  dependsOn:
    - name: automation
  sourceRef:
    kind: GitRepository
    name: flux-system
