apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-database
  namespace: linkwarden
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-minimal-trixie@sha256:7497531472a822f5f49b701f9d5f7f6735e8d139a35f534cd540bf5dd6c63d29
  instances: 1
  bootstrap:
    initdb:
      database: linkwarden
      owner: linkwarden
      secret:
        name: linkwarden-database
  storage:
    size: 5Gi
    storageClass: local-path
