apiVersion: automation.excloo.dev/v1alpha1
kind: PrivateDNSRecord
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  hostname: links.excloo.com
  ipv6Enabled: false
  crossplane:
    compositionRef:
      name: private-dns-record-control-d-only
