apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 30m
  releaseName: onepassword-connect
  chart:
    spec:
      chart: connect
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
      version: 2.4.1
  install:
    skipCRDs: true
  values:
    connect:
      credentialsName: onepassword-connect
    operator:
      create: false
