apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlagent-victoria-metrics-k8s-stack
subjects:
  - kind: ServiceAccount
    name: vlagent-victoria-metrics-k8s-stack
    namespace: observability-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vlagent-victoria-metrics-k8s-stack
