apiVersion: v1
kind: Namespace
metadata:
  name: sidestore-vpn
  labels:
    app.kubernetes.io/name: sidestore-vpn
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sidestore-vpn
  namespace: sidestore-vpn
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: SideStore VPN
        property: auth-key
      secretKey: TS_AUTHKEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: sidestore-vpn
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sidestore-vpn
  namespace: sidestore-vpn
spec:
  ingress:
    - ports:
        - port: 41641
          protocol: UDP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sidestore-vpn
  policyTypes:
    - Ingress
