apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: observability
spec:
  values:
    vmagent:
      spec:
        externalLabels:
          cluster: syd
