apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
  namespace: pocket-id
  annotations:
    onepassword.excloo.dev/adopt-titles: Excloo ID (pocket-id),pocket-id
    onepassword.excloo.dev/constants: '{"database-username":"pocket-id"}'
    onepassword.excloo.dev/generate-fields: database-password,encryption-key,static-api-key
    onepassword.excloo.dev/migrate-fields: '{"encryption_key":"encryption-key","mail_password":"api-key-resend","static_api_key":"static-api-key"}'
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Excloo ID
        property: api-key-resend
      secretKey: api-key-resend
    - remoteRef:
        key: Excloo ID
        property: database-password
      secretKey: database-password
    - remoteRef:
        key: Excloo ID
        property: database-username
      secretKey: database-username
    - remoteRef:
        key: Excloo ID
        property: encryption-key
      secretKey: encryption-key
    - remoteRef:
        key: Excloo ID
        property: static-api-key
      secretKey: static-api-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: pocket-id
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_STRING: 'postgresql://{{ index . "database-username" | urlquery }}:{{ index . "database-password" | urlquery }}@pocket-id-database-rw:5432/pocket-id?sslmode=require'
        ENCRYPTION_KEY: '{{ index . "encryption-key" }}'
        SMTP_PASSWORD: '{{ index . "api-key-resend" }}'
        STATIC_API_KEY: '{{ index . "static-api-key" }}'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-database
  namespace: pocket-id
  annotations:
    onepassword.excloo.dev/constants: '{"database-username":"pocket-id"}'
    onepassword.excloo.dev/generate-fields: database-password
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Excloo ID
        property: database-password
      secretKey: password
    - remoteRef:
        key: Excloo ID
        property: database-username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: pocket-id-database
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
