apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  interval: 30m
  releaseName: pocket-id
  chart:
    spec:
      chart: app-template
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 5.2.1
  values:
    controllers:
      pocket-id:
        strategy: Recreate
        containers:
          pocket-id:
            envFrom:
              - secretRef:
                  name: pocket-id
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/pocket-id/pocket-id
              tag: v2.18.0@sha256:323e7ef5bfacf7cf32f22f3d10ccdf48e0c97c94d67e7e40b0b996830deb5165
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  exec:
                    command:
                      - /app/pocket-id
                      - healthcheck
                  failureThreshold: 3
                  periodSeconds: 30
                  timeoutSeconds: 5
              readiness:
                custom: true
                enabled: true
                spec:
                  exec:
                    command:
                      - /app/pocket-id
                      - healthcheck
                  failureThreshold: 3
                  periodSeconds: 10
                  timeoutSeconds: 5
              startup:
                custom: true
                enabled: true
                spec:
                  exec:
                    command:
                      - /app/pocket-id
                      - healthcheck
                  failureThreshold: 30
                  periodSeconds: 2
                  timeoutSeconds: 5
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 20m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsGroup: 568
              runAsNonRoot: true
              runAsUser: 568
              capabilities:
                drop:
                  - ALL
            env:
              APP_URL: https://app.invalid
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
    global:
      nameOverride: pocket-id
    persistence:
      temporary:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      private:
        hostnames:
          - app.invalid
        labels:
          app.kubernetes.io/name: pocket-id
        parentRefs:
          - name: private
            namespace: networking
        rules:
          - backendRefs:
              - name: pocket-id
                port: 1411
      public:
        forceRename: pocket-id
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          gethomepage.dev/href: https://app.invalid
        labels:
          app.kubernetes.io/name: pocket-id
          gateway.excloo.dev/public-access: "true"
        parentRefs:
          - name: public-tunnel
            namespace: networking
        hostnames:
          - identity.invalid
    service:
      pocket-id:
        controller: pocket-id
        ports:
          http:
            port: 1411
            protocol: HTTP
