apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: pocket-id
  annotations:
    k8s-sigs.io/nfs-directory-gid: "568"
    k8s-sigs.io/nfs-directory-mode: "0770"
    k8s-sigs.io/nfs-directory-uid: "568"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nfs
