apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  values:
    route:
      public:
        annotations:
          gethomepage.dev/description: OIDC Provider
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/icon: pocket-id
          gethomepage.dev/name: Pocket ID
          monitoring.excloo.dev/enabled: "true"
    controllers:
      pocket-id:
        containers:
          pocket-id:
            env:
              ALLOW_OWN_ACCOUNT_EDIT: "true"
              ANALYTICS_DISABLED: "true"
              APP_NAME: Pocket ID
              EMAILS_VERIFIED: "true"
              FILE_BACKEND: database
              REQUIRE_USER_EMAIL: "true"
              SMTP_FROM: pocket-id@excloo.dev
              SMTP_HOST: smtp.resend.com
              SMTP_PORT: "465"
              SMTP_TLS: tls
              SMTP_USER: resend
              TRUST_PROXY: "true"
              UI_CONFIG_DISABLED: "true"
              VERSION_CHECK_DISABLED: "true"
              WEBAUTHN_ALLOW_SYNCED_PASSKEYS: "true"
              WEBAUTHN_USER_VERIFICATION: required
