apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
  namespace: open-webui
  annotations:
    onepassword.excloo.dev/adopt-titles: Open WebUI
    onepassword.excloo.dev/defaults: '{"admin-email":"max@excloo.com","admin-name":"Max"}'
    onepassword.excloo.dev/generate-fields: password,webui-secret-key
    onepassword.excloo.dev/migrate-fields: '{"oidc_client_id":"oidc-client-id","oidc_client_secret":"oidc-client-secret","webui_secret_key":"webui-secret-key"}'
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Open WebUI
        property: admin-email
      secretKey: WEBUI_ADMIN_EMAIL
    - remoteRef:
        key: Open WebUI
        property: admin-name
      secretKey: WEBUI_ADMIN_NAME
    - remoteRef:
        key: Open WebUI
        property: oidc-client-id
      secretKey: OAUTH_CLIENT_ID
    - remoteRef:
        key: Open WebUI
        property: oidc-client-secret
      secretKey: OAUTH_CLIENT_SECRET
    - remoteRef:
        key: Open WebUI
        property: password
      secretKey: WEBUI_ADMIN_PASSWORD
    - remoteRef:
        key: Open WebUI
        property: webui-secret-key
      secretKey: WEBUI_SECRET_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: open-webui
