apiVersion: automation.excloo.dev/v1alpha1
kind: PocketIDClient
metadata:
  name: open-webui
  namespace: open-webui
spec:
  client:
    callbackURLs:
      - https://app.invalid/oauth/oidc/callback
    description: AI Chat
    id: open-webui-au-truenas
    launchURL: https://app.invalid
    name: Open WebUI
    pkceEnabled: true
