apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra
  namespace: papra
spec:
  data:
    - remoteRef:
        key: papra/auth-providers-customs
      secretKey: AUTH_PROVIDERS_CUSTOMS
    - remoteRef:
        key: papra/password
      secretKey: AUTH_SECRET
    - remoteRef:
        key: papra/openrouter-api-key
      secretKey: OPENROUTER_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: papra
