apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra
  namespace: papra
  annotations:
    onepassword.excloo.dev/generate-fields: auth-secret
    onepassword.excloo.dev/migrate-fields: '{"password":"auth-secret"}'
    onepassword.excloo.dev/remove-fields: password,username
spec:
  data:
    - remoteRef:
        key: Papra
        property: auth-providers-customs
      secretKey: AUTH_PROVIDERS_CUSTOMS
    - remoteRef:
        key: Papra
        property: auth-secret
      secretKey: AUTH_SECRET
    - remoteRef:
        key: Papra
        property: api-key-openrouter
      secretKey: OPENROUTER_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: papra
