apiVersion: v1
kind: PersistentVolume
metadata:
  name: papra-data
  labels:
    app.kubernetes.io/name: papra
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/truenas-nvme/papra
    server: 10.4.0.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
