apiVersion: automation.excloo.dev/v1alpha1
kind: PocketIDClient
metadata:
  name: papra
  namespace: papra
spec:
  client:
    callbackURLs:
      - https://app.invalid/api/auth/oauth2/callback/pocket-id
    description: Document Management
    id: papra-au-truenas
    launchURL: https://app.invalid
    name: Papra
    pkceEnabled: true
