apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra
  namespace: papra
  annotations:
    onepassword.excloo.dev/generate-fields: auth-secret
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Papra
        property: auth-providers-customs
      secretKey: AUTH_PROVIDERS_CUSTOMS
    - remoteRef:
        key: Papra
        property: auth-secret
      secretKey: AUTH_SECRET
    - remoteRef:
        key: Papra
        property: api-key-openrouter
      secretKey: OPENROUTER_API_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: papra
---
apiVersion: v1
kind: Namespace
metadata:
  name: papra
  labels:
    app.kubernetes.io/name: papra
    gateway.excloo.dev/private-access: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: papra
  namespace: papra
  labels:
    app.kubernetes.io/name: papra
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: networking
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 21221
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: papra
  policyTypes:
    - Ingress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: papra
  annotations:
    k8s-sigs.io/nfs-directory-gid: "568"
    k8s-sigs.io/nfs-directory-mode: "0700"
    k8s-sigs.io/nfs-directory-uid: "568"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retained-data
  namespace: papra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: papra-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: papra-data
  labels:
    app.kubernetes.io/name: papra
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/truenas-nvme/papra
    server: 10.4.0.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
