apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-crossplane
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: cloudflare-crossplane/password
      secretKey: token
    - remoteRef:
        key: cloudflare-crossplane/username
      secretKey: zone-id
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: cloudflare-crossplane
