apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-waf-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Cloudflare WAF
        property: password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-waf-credentials
    template:
      engineVersion: v2
      data:
        authorization: "Bearer {{ .password }}"
