apiVersion: http.m.crossplane.io/v1alpha2
kind: ClusterProviderConfig
metadata:
  name: cloudflare-app-policy
spec:
  credentials:
    source: Secret
    secretRef:
      key: authorization
      name: cloudflare-app-policy-credentials
      namespace: crossplane-system
