apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Backblaze B2
        property: username
      secretKey: username
    - remoteRef:
        key: Backblaze B2
        property: password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: b2-credentials
    template:
      engineVersion: v2
      data:
        authorization: 'Basic {{ printf "%s:%s" .username .password | b64enc }}'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-waf-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Cloudflare WAF
        property: password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-waf-credentials
    template:
      engineVersion: v2
      data:
        authorization: "Bearer {{ .password }}"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: control-d-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Control D
        property: password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: control-d-credentials
    template:
      engineVersion: v2
      data:
        authorization: "Bearer {{ .password }}"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resend-credentials
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Resend
        property: password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: resend-credentials
    template:
      engineVersion: v2
      data:
        authorization: "Bearer {{ .password }}"
