apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: onepassword-connect
            namespace: external-secrets
      vaults: {}
