apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      auth:
        serviceAccountSecretRef:
          key: token
          name: onepassword-sdk
          namespace: external-secrets
      vault: 6bit6kovpdqaja5qilki5u2hvm
