apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: immich-database
  namespace: immich
spec:
  allowRepeat: true
  digits: 12
  length: 48
  noUpper: false
  symbols: 12
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-database
  namespace: immich
spec:
  deletionPolicy: None
  refreshInterval: 1h
  updatePolicy: IfNotExists
  data:
    - match:
        remoteRef:
          remoteKey: database-immich
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          tags: [Homelab, Database, Immich]
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: onepassword
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: immich-database
  template:
    engineVersion: v2
    data:
      password: "{{ .password }}"
      username: immich
