apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-database
  namespace: immich
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Immich
        property: password
      secretKey: password
    - remoteRef:
        key: Immich
        property: username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: immich-database
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
