apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-database
  namespace: immich
  annotations:
    onepassword.excloo.dev/constants: '{"database-username":"immich"}'
    onepassword.excloo.dev/generate-fields: database-password
    onepassword.excloo.dev/migrate-fields: '{"password":"database-password","username":"database-username"}'
    onepassword.excloo.dev/remove-fields: password,username
spec:
  refreshInterval: 1h
  data:
    - remoteRef:
        key: Immich
        property: database-password
      secretKey: password
    - remoteRef:
        key: Immich
        property: database-username
      secretKey: username
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Retain
    name: immich-database
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        password: "{{ .password }}"
        username: "{{ .username }}"
