apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  releaseName: immich
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            env:
              DB_DATABASE_NAME: immich
              DB_HOSTNAME: immich-database-rw
              DB_PORT: "5432"
              DB_SSL_MODE: require
              DB_VECTOR_EXTENSION: vectorchord
              IMMICH_LOG_FORMAT: json
              TZ: Australia/Sydney
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: immich-database
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    key: username
                    name: immich-database
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        supplementalGroups:
          - 3000
        seccompProfile:
          type: RuntimeDefault
    immich:
      persistence:
        library:
          existingClaim: library
    machine-learning:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: v3.2.2@sha256:60dfcf266a9ef3b7376f5678e8c980d4fb61db5fc48c078fe8a326ab1535d60d
              resources:
                limits:
                  memory: 4Gi
                requests:
                  cpu: 100m
                  memory: 1Gi
      persistence:
        cache:
          accessMode: ReadWriteOnce
          size: 10Gi
          storageClass: local-path
          type: persistentVolumeClaim
    server:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                tag: v3.2.2@sha256:79cc1623323d5894922686d8743b4780181428f98eecbfb58ce12c41ef02d1ea
              resources:
                limits:
                  memory: 4Gi
                requests:
                  cpu: 100m
                  memory: 1Gi
      persistence:
        cli:
          enabled: true
          type: emptyDir
          globalMounts:
            - path: /.config
        icloud-photos:
          enabled: true
          existingClaim: icloud-photos
          type: persistentVolumeClaim
          globalMounts:
            - path: /icloud-photos
              readOnly: true
        temporary:
          enabled: true
          type: emptyDir
          globalMounts:
            - path: /tmp
    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: docker.io/valkey/valkey
                tag: 9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
              resources:
                limits:
                  memory: 512Mi
                requests:
                  cpu: 20m
                  memory: 128Mi
