apiVersion: automation.excloo.dev/v1alpha1
kind: PocketIDClient
metadata:
  name: immich
  namespace: immich
spec:
  client:
    callbackURLs:
      - app.immich:///oauth-callback
      - https://app.invalid/auth/login
      - https://app.invalid/user-settings
    description: Photo Manager
    id: immich-au-truenas
    launchURL: https://app.invalid
    name: Immich
