apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 30m
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
      version: 2.4.0
  values:
    extraObjects:
      - apiVersion: pkg.crossplane.io/v1beta1
        kind: DeploymentRuntimeConfig
        metadata:
          name: default
        spec:
          deploymentTemplate:
            spec:
              selector: {}
              template:
                spec:
                  containers:
                    - name: package-runtime
                      resources:
                        requests:
                          cpu: 20m
                          memory: 64Mi
                        limits:
                          memory: 256Mi
                      securityContext:
                        allowPrivilegeEscalation: false
                        readOnlyRootFilesystem: true
                        runAsNonRoot: true
                        capabilities:
                          drop: [ALL]
                        seccompProfile:
                          type: RuntimeDefault
    function:
      packages:
        [
          xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.8.2,
        ]
    provider:
      packages: [xpkg.upbound.io/crossplane-contrib/provider-http:v1.0.14]
    resourcesCrossplane:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
    resourcesRBACManager:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 256Mi
    securityContextCrossplane:
      runAsNonRoot: true
      capabilities:
        drop: [ALL]
      seccompProfile:
        type: RuntimeDefault
    securityContextRBACManager:
      runAsNonRoot: true
      capabilities:
        drop: [ALL]
      seccompProfile:
        type: RuntimeDefault
